# Server
server.port=8080

# Database Configuration (Using Render Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect






# Show SQL in logs
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session In View (recommended for APIs)
spring.jpa.open-in-view=false




#
#spring.datasource.url=jdbc:mysql://localhost:3306/hms
#spring.datasource.username=root
#spring.datasource.password=safwan123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
### PostgreSQL Driver
#

# JPA / Hibernate
jwt.secretKey=mysupersecretjwtkeymysupersecretjwtkey123
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
